apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
  - name: localhost:5001/middleman-workflows
    newName: ghcr.io/pokt-network/middleman-workflows
    newTag: "0.6.0"
patches:
  - path: ./patches/configmap.yaml
  - target:
      kind: Deployment
      name: middleman-workflows
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: "IfNotPresent"
