apiVersion: v1
kind: Secret
metadata:
  name: middleman-secrets
type: Opaque
stringData:
  AUTH_SECRET: "<path:vaults/4e23ltnymsocewfvsu3gb6iika/items/qjyq3b5dmcucpxhfkpd2dfrzfe#auth_secret>"
  COIN_MARKET_CAP_API_KEY: "<path:vaults/4e23ltnymsocewfvsu3gb6iika/items/d4euj4npgi4gjec6c52rhgtmnm#credential>"
  APP_IDENTITY: "<path:vaults/4e23ltnymsocewfvsu3gb6iika/items/qahbboircuzqrfoftltz7qnmzm#private_key>"
