apiVersion: v1
kind: Secret
metadata:
  name: postgres-middleman-connection
type: Opaque
stringData:
  PGHOST: "rw-pooler.postgresql.svc.cluster.local"
  PGUSER: "<path:vaults/4e23ltnymsocewfvsu3gb6iika/items/xirirjjtrxllvn3wburl5j34ny#username>"
  PGPASSWORD: "<path:vaults/4e23ltnymsocewfvsu3gb6iika/items/xirirjjtrxllvn3wburl5j34ny#password>"
  DATABASE_URL: "postgresql://<path:vaults/4e23ltnymsocewfvsu3gb6iika/items/xirirjjtrxllvn3wburl5j34ny#username>:<path:vaults/4e23ltnymsocewfvsu3gb6iika/items/xirirjjtrxllvn3wburl5j34ny#password>@rw-pooler.postgresql.svc.cluster.local:5432/igniter-middleman-staging?sslmode=disable"
  DB_NAME: "igniter-middleman-staging"
  PGADMIN_DB: "postgres"
  PG_POOL_MAX: "3"
  PG_POOL_MIN: "1"
