apiVersion: v1
kind: ConfigMap
metadata:
  name: middleman-workflows-config
data:
  TEMPORAL_URL: "<path:vaults/4e23ltnymsocewfvsu3gb6iika/items/odckcmmxife3kksgpicjzhpooe#server>:<path:vaults/4e23ltnymsocewfvsu3gb6iika/items/odckcmmxife3kksgpicjzhpooe#port>"
  TEMPORAL_NAMESPACE: "middleman-mainnet"
  TEMPORAL_TASK_QUEUE: "operations"
  TEMPORAL_WORKFLOW_RETENTION: "604800"
  POKT_RPC_URL: "https://sauron-rpc.infra.pocket.network"
  PROVIDERS_CDN_URL: "https://raw.githubusercontent.com/pokt-network/igniter-governance/refs/heads/main/pocket/provider.json"
