apiVersion: v1
kind: Secret
metadata:
  name: middleman-secrets
stringData:
  AUTH_SECRET: "6c5p6eyjnbD9JzgfcxvhaIGgu3jMCakNhDw604bW9ZQ="
  COIN_MARKET_CAP_API_KEY: "d8221f1c-02c2-4016-849f-f3cd842d1e83"
  # Notification channel secret-at-rest encryption (DEV). Distinct from provider's key.
  NOTIFICATION_ENCRYPTION_KEY: "511b72e6296109295e0df03fa17f122cd8116f6cbba7030b135b93bddab89f8c"
