apiVersion: v1
kind: ConfigMap
metadata:
  name: provider-config
data:
  DELEGATORS_CDN_URL: "https://soothe-vault.nyc3.cdn.digitaloceanspaces.com/{chainId}/delegators.json"
  AUTH_TRUST_HOST: "true"
  APP_URL: "http://localhost:3001"
  AUTH_URL: "http://localhost:3001"
  OWNER_IDENTITY: "CHANGE_THIS"
  CHAIN_ID: "pocket"
  BLOCKCHAIN_PROTOCOL: "shannon"
  OWNER_EMAIL: "CHANGE_THIS"
  TEMPORAL_URL: "temporal-frontend.default.svc.cluster.local:7233"
  TEMPORAL_NAMESPACE: "provider"
  TEMPORAL_TASK_QUEUE: "provider-operations"
  MAINNET_INDEXER_API_URL: "https://data.pocket.network/"
  BETA_INDEXER_API_URL: "https://data.beta.pocket.network/"
  ALPHA_INDEXER_API_URL: "https://data.alpha.pocket.network/"
  MINIMUM_STAKE_BUFFER: "2000000"
